### ISSUE TITLE
Extending GUI with button interface

### ISSUE THREAD

**Issue by archenroot** [jaredly/hexo-admin#110] opened 2017-01-24 09:10 UTC
Hi guys,

first thanks for hexo-admin. I started with this cool and simple tool back in time, but found one issue :-), more personal one than technical one. While in the beginning I learned the syntax for formatting the content, I forgot that during time (I am not writing articles on daily basis, but more on monthly or more), so each time I have to open some cheat-sheet and looking again what am I doing.

It would be great hexo-admin has markdown gui interface (buttons, comboboxes, etc.).

Would you consider to implement something like this in near future?

Thanks for this tool.

Ladislav

**Comment by newbiebt** [comment] 2017-01-25 00:30
you mean like #88 ?
![123](https://cloud.githubusercontent.com/assets/13112518/22272960/871a304e-e2d8-11e6-903e-8e6fd4de23a2.png)

**Comment by archenroot** [comment] 2017-01-25 11:48
Yes, exactly.

**Comment by PirtleShell** [comment] 2017-01-31 17:24
I'm going to close this as a duplicate of #88. We can discuss it further there.

**Closed by PirtleShell** 2017-01-31 17:24 UTC
