### ISSUE TITLE
It will be great if it supports markdown toolbar

### ISSUE THREAD

**Issue by bejondshao** [jaredly/hexo-admin#166] opened 2018-05-09 02:47 UTC
Thanks to the plugin and makes me edit posts without other editors. If it supports markdown tags toolbar would be perfect. Nearly 1K starts, I believe a lot of people want this feature. Thank you.

**Comment by melvinthoabala** [comment] 2018-05-16 12:33
This will be a cool feature 🚀

**Comment by fadehelix** [comment] 2018-06-22 16:43
I think that this is related to #88 ;) 
IMHO the main blocker for this feature is a deprecated React version and workflow (would be better to use Webpack instead of Browserify). I am going to do this, but it is not as easy I want and would be great if someone else could help ;)

**Comment by pirtleshell** [comment] 2018-08-11 00:48
thanks for the suggestion. closing as duplicate of #88

**Closed by pirtleshell** 2018-08-11 00:48 UTC
